# Generated by Django 3.2 on 2022-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='agentphoto')),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
