# Generated by Django 4.0.6 on 2023-02-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_user'),
        ('pages', '0003_category_property_tag_tweet_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytag',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
