# Generated by Django 4.0.6 on 2023-03-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.blog')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.tag')),
            ],
        ),
    ]
